version: "3"

services:
  spotilist_db:
    image: postgres
    container_name: spotilist_db
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_DB=$DB_NAME
    volumes:
      - dbdata:/data/spotilist_db

volumes:
  dbdata:
